language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache/files

git:
  depth: 5

php:
  - 5.3.3
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm
  - nightly

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly

before_script:
  - rm -f ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini
  - flags=""
  - if [ `phpenv version-name` == "5.3.3" ]; then flags="--ignore-platform-reqs"; fi
  - composer install $flags --no-interaction --no-progress --prefer-dist

script:
  - vendor/bin/phpunit
